# Bun CLI configuration file
# https://bun.sh/docs/runtime/bunfig

# Equivalent of DO_NOT_TRACK env variable.
telemetry = false

# Reduce memory usage at the cost of performance
smol = false

[install.cache]
# the directory to use for the cache
dir = "$CACHE/bun"

# when true, don't load from the global cache.
# Bun may still write to node_modules/.cache
disable = false

# when true, always resolve the latest versions from the registry
disableManifest = false
