[include]
# paths = ["/etc/topgrade.toml"]

[misc]
disable = ["system", "containers", "yarn", "pip3", "skills", "claude_code", "mas"]

display_time = true
ask_retry = false
cleanup = true
no_self_update = true

# When to send a notification at the end of a run (default: "always")
notify_end = "on_failure"

# Show the reason for skipped steps (default: false)
# show_skipped = true

[pre_commands]
# "Before" = "some command"

[post_commands]
"Docker Prune" = "docker system prune -f 2>&1 | tail -1"

[commands]
# "Custom" = "some command"

[python]
# enable_pip_review = true
# enable_pipupgrade = true

[conda]
# env_names = ["Toolbox"]

[composer]
# self_update = true

[brew]
autoremove = true
greedy_cask = false
greedy_latest = false

[git]
max_concurrency = 8
repos = ["~/Developer/*/*/"]
pull_predefined = false
# arguments = "--rebase --autostash"
fetch_only = true

[npm]
# use_sudo = true

[deno]
# version = "stable"

[vim]
# force_plug_update = true

[firmware]
# upgrade = true

[containers]
# ignored_containers = ["docker.io*"]
# runtime = "podman"
# system_prune = false
# use_sudo = false

[lensfun]
# use_sudo = false

[vscode]
# profile = ""

[pixi]
# include_release_notes = false

[mise]
bump = true
jobs = 8
interactive = false

[go]
# gup_exclude = ["kind", "pkgsite"]

[cargo]
# git = false
quiet = true

[rustup]
channels = ["stable"]

[doom]
# aot = true
